# Generated by Django 5.1.7 on 2026-05-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpackages',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='packages_images/'),
        ),
    ]
