# Generated by Django 5.1.7 on 2026-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='responseMessage',
            field=models.TextField(blank=True),
        ),
    ]
