# Generated by Django 5.1.7 on 2026-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_generalpackages_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpackages',
            name='attractions',
            field=models.ManyToManyField(related_name='packages', through='travel_app.PackagesAttraction', to='travel_app.attraction'),
        ),
        migrations.AlterField(
            model_name='packagesattraction',
            name='day',
            field=models.PositiveIntegerField(),
        ),
    ]
