# Generated by Django 5.1.7 on 2026-06-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_newsletter_alter_booking_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='NewsletterSubscriber',
        ),
    ]
